### PR TITLE
Dev1

### PR DESCRIPTION
**Pull request by olimeise**

### CODE REVIEW

**Comment by AlexFilipin** [comment]
Hi @olimeise can you provide some insights for these changes? Seems like nothing is changed?

**Comment by AlexFilipin** [comment]
Oh seems like you commented out the connect path

**Comment by olimeise** [comment]
Sorry, I actually wanted to change something in my fork. Github is still pretty new for me.  Very good work by the way.

**Comment by AlexFilipin** [comment]
No worries, glad you are finding value

**Pull request closed without merging**
